defaults:
  - configs/dockerfile@dockerfile
  - configs/workload@workload
  - configs/slurm@slurm
  - _self_ # needs to be last to enable overriding

dockerfile:
  base_image: "MY_BASE_IMAGE"

workload:
  num_epochs: "AAAAAA"

slurm:
  job_name: "ZZZZ"
