job_scheduler:
  type: "slurm"
  slurm:
    env_vars:
      SLURM_PROCID: "0"
      WORLD_SIZE: "1"
      GPUS_PER_NODE: "${env:GPUS_PER_NODE,1}" # Can be overridden dynamically
  slurm_options:
    partition: "gpu"
    nodes: 1
    ntasks: 1
    time: "02:00:00"
