type: "huggingface"
requirements:
  - transformers
  - datasets
  - torch
env_vars:
  HF_DATASETS_CACHE: "/mnt/shared/datasets_cache"
cmd: "bash workload.sh"
script: "hf.py"
model_name: "bert-base-uncased"
task: "text-classification"
learning_rate: 5e-5
batch_size: 16
num_epochs: 3
training:
  dataset: "glue"
  dataset_config: "mrpc"
  batch_size: 16
  num_epochs: 3
  learning_rate: 5e-5
environment:
  use_gpu: true
  num_gpus: 1
output:
  model_save_path: "/workspace"
  results_save_path: "/workspace"
additional_args: ""
