slurm:
  job_name: "default_slurm_job"
  partition: "devel"
  nodes: 2
  ntasks: 8
  time: "01:00:00"
  # ... other SLURM default configurations ...

kubernetes:
  job_file: "/path/to/k8_job.yaml"
  # ... other Kubernetes default configurations ...
